#!/bin/bash
#
# Program: Cloudflare_V4 API manage
# Author: shazi
AuthKey="32395b2d113046ba1fee7afe960as4ddbe9ac"
AuthEmail="user@email.com"
APIURI="https://api.cloudflare.com/client/v4/zones"

# env
python="/usr/bin/python"

declare -a callopts

helpmsg() {
    echo ""
    echo "Usage: $0 [CONFIG] [ACTION]"
    echo ""
    echo "CONFIG:"
    echo "-d                Set domain."
    echo ""
    echo "ACTION:"
    echo "cache             remove cache everything."
    echo "show              show information. [status|dns]"
    echo ""
}

call_cf() {
    callopts+=(-H "X-Auth-Email: $AuthEmail")
    callopts+=(-H "X-Auth-Key: $AuthKey")
    callopts+=(-H "Content-Type: application/json")
    curl "${APIURI}/${identifier}/${APIPATH}" "${callopts[@]}" 2>/dev/null "$@"
}

get_id() {
    local APIPATH callheader
    callheader+=(-X GET)
    APIPATH="?name=$domain&status=active&page=1&per_page=20&order=status&direction=desc&match=all"
    identifier=`call_cf | jsoncode | sort | grep \"id\" \
    | tail -1 | awk -F \" '{print $(NF-1)}'`
}

pure_cache(){
    get_id
    APIPATH="purge_cache"
    callopts+=(-X DELETE)
    call_cf --data {\"$1\":true} | awk -F \" '{print "cache status"$9}'
}

query(){
    get_id
    APIPATH=$1
    call_cf | jsoncode
}

jsoncode() {
    $python -m json.tool
}


cmd1=$1
shift

case $cmd1 in
    -d)   
        [ -z $1 ] && echo "Usage: option \"-d\" need set domain." && exit 0
        domain=$1
        shift
        if [[ -z $1 ]]; then
            echo -e "Commands:\n    cache, show"
        else
            cmd2=$1
            shift
        fi

        case $cmd2 in
            cache)
                # clean purge everything
                pure_cache purge_everything
                ;;
            show)
                if [[ -z $1 ]]; then
                    echo -e "Parameters:\n    status, dns"
                else
                    cmd3=$1
                    shift
                fi
                
                case $cmd3 in
                    status)
                        # default query status
                        query "?name=$domain&status=active&page=1&per_page=20&order=status&direction=desc&match=all"
                        ;;
                    dns)
                        query "dns_records"
                        ;;
                esac
                ;;
        esac
        ;;
    -h|--help|*)
        helpmsg
        ;;
esac

